global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: service-1
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - service-1:8081
  - job_name: service-2
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - service-2:8082